Repository curator-OEUVRE/OEUVRE-client, pull requests merged in 2022-11, with the labels that each got.

#49 feat: add profile screen
  assets/icons/AddFloor.tsx
  assets/icons/AddPicture.tsx
  assets/icons/Alert.tsx
  assets/icons/BookmarkFilled.tsx
  assets/icons/Floor.tsx
  assets/icons/Person.tsx
  assets/icons/PersonOff.tsx
  assets/icons/Setting.tsx
  package.json
  src/apis/common.ts
  src/apis/floor.ts
  src/apis/user.ts
  src/components/BottomSheet/index.tsx
  src/components/Header/index.tsx
  src/components/SettingItem/index.tsx
  src/constants/screens.ts
  src/constants/styles/sizes.ts
  src/constants/styles/textStyles.ts
  src/feature/Collection/Collection.stories.tsx
  src/feature/Collection/index.tsx
  src/feature/FloorList/FloorList.stories.tsx
  src/feature/FloorList/FloorListItem.tsx
  src/feature/FloorList/index.tsx
  src/feature/FloorPictureList/index.tsx
  src/feature/ProfileCard/ProfileCard.stories.tsx
  src/feature/ProfileCard/index.tsx
  src/feature/Routes/FloorStack.tsx
  src/feature/Routes/MainTabNavigator.tsx
  src/feature/Routes/ProfileStack.tsx
  src/feature/Routes/index.tsx
  src/hooks/useAuth.ts
  src/screens/CreateFloorScreen/FloorInfoFormScreen.tsx
  src/screens/EditProfileScreen/index.tsx
  src/screens/ProfileScreen/MyProfileScreen.tsx
  src/screens/ProfileScreen/ProfileTemplate.tsx
  src/screens/ProfileScreen/WrappedFloorList.tsx
  src/screens/ProfileScreen/index.tsx
  src/screens/SettingScreen/index.tsx
  src/states/authStore.ts
  src/states/signUpStore.tsx
  src/states/userStore.ts
  src/types/floor.ts
  src/types/user.ts
  storybook/storyLoader.js
  yarn.lock
Labels: feature, api

#51 Feat: like-user-sheet
  src/apis/picture.ts
  src/components/BottomSheet/index.tsx
  src/feature/UserProfileList/index.tsx
  src/screens/FloorScreen/EditFloorScreen.tsx
  src/screens/ImageDetailScreen/index.tsx
  src/types/picture.ts
Labels: feature

#52 feat: edit-description-screen
  src/components/Header/index.tsx
  src/constants/screens.ts
  src/feature/FloorPictureList/FloorPicture.tsx
  src/feature/PictureDescriptionList/index.tsx
  src/feature/Routes/FloorStack.tsx
  src/screens/CreateFloorScreen/AddHashtagScreen.tsx
  src/screens/CreateFloorScreen/AddPictureScreen.tsx
  src/screens/CreateFloorScreen/FloorInfoFormScreen.tsx
  src/screens/CreateFloorScreen/PictureDescriptionScreen.tsx
  src/screens/FloorScreen/EditDescriptionScreen.tsx
  src/screens/FloorScreen/EditFloorScreen.tsx
  src/screens/FloorScreen/FloorViewerScreen.tsx
  src/screens/FloorScreen/index.tsx
  src/screens/ProfileScreen/MyProfileScreen.tsx
  src/states/createFloorStore.tsx
Labels: feature

#55 fix: fix critical test issues
  assets/icons/AddCircle.tsx
  assets/icons/AddProfile.tsx
  src/apis/user.ts
  src/components/FormInput/index.tsx
  src/components/UserInputLayout/index.tsx
  src/constants/common/index.ts
  src/feature/FloorList/index.tsx
  src/feature/FloorTicket/index.tsx
  src/feature/PersonalDataForm/index.tsx
  src/feature/ProfileCard/index.tsx
  src/feature/TermsForm/index.tsx
  src/feature/UserProfileForm/index.tsx
  src/screens/HomeScreen/index.tsx
  src/screens/SignUpScreen/UserProfileFormScreen.tsx
  src/screens/WelcomeScreen/index.tsx
  src/services/validation/signUp.ts
  src/states/signUpStore.tsx
Labels: bug, feature, api

#57 Fix: issue 3
  src/feature/FloorPictureList/FloorPicture.tsx
  src/feature/FloorPictureList/index.tsx
  src/feature/PictureDescriptionList/PictureDescriptionItem.tsx
  src/feature/Routes/FloorStack.tsx
  src/feature/Routes/HomeStack.tsx
  src/screens/CreateFloorScreen/AddPictureScreen.tsx
  src/screens/CreateFloorScreen/FloorInfoFormScreen.tsx
  src/screens/CreateFloorScreen/PictureDescriptionScreen.tsx
  src/screens/FloorScreen/EditDescriptionScreen.tsx
  src/screens/FloorScreen/EditFloorScreen.tsx
  src/screens/FloorScreen/FloorViewerScreen.tsx
  src/screens/GuestBookScreen/index.tsx
  src/screens/ImageDetailScreen/index.tsx
  src/screens/ProfileScreen/MyProfileScreen.tsx
  src/states/createFloorStore.tsx
Labels: bug

#58 feat: add search feature
  assets/icons/Close.tsx
  assets/icons/NormalHashtag.tsx
  assets/icons/Search.tsx
  src/apis/floor.ts
  src/apis/hashtag.ts
  src/apis/user.ts
  src/constants/screens.ts
  src/feature/Routes/ExplorationStack.tsx
  src/feature/Routes/MainTabNavigator.tsx
  src/feature/SearchInput/SearchInput.stories.tsx
  src/feature/SearchInput/index.tsx
  src/screens/ExplorationScreen/HashtagListItem.tsx
  src/screens/ExplorationScreen/index.tsx
  src/screens/ProfileScreen/MyProfileScreen.tsx
  src/screens/SearchScreen/FloorSearchResult.tsx
  src/screens/SearchScreen/HashtagSearchResult.tsx
  src/screens/SearchScreen/SearchResultTemplate.tsx
  src/screens/SearchScreen/UserSearchResult.tsx
  src/screens/SearchScreen/index.tsx
  src/types/common.ts
  storybook/storyLoader.js
Labels: feature, api

#60 feat: add onboarding & resolve issues
  app.config.js
  assets/images/onboarding1.png
  assets/images/onboarding1@2x.png
  assets/images/onboarding1@3x.png
  assets/images/onboarding2.png
  assets/images/onboarding2@2x.png
  assets/images/onboarding2@3x.png
  assets/images/onboarding3.png
  assets/images/onboarding3@2x.png
  assets/images/onboarding3@3x.png
  assets/images/onboarding4.png
  assets/images/onboarding4@2x.png
  assets/images/onboarding4@3x.png
  assets/images/onboarding5.png
  assets/images/onboarding5@2x.png
  assets/images/onboarding5@3x.png
  package.json
  src/components/FormInput/index.tsx
  src/constants/common/index.ts
  src/constants/images.ts
  src/constants/screens.ts
  src/constants/styles/textStyles.ts
  src/feature/PersonalDataForm/index.tsx
  src/feature/Routes/AuthStack.tsx
  src/feature/Routes/MainTabNavigator.tsx
  src/feature/UserProfileForm/index.tsx
  src/screens/CreateFloorScreen/AddPictureScreen.tsx
  src/screens/EditProfileScreen/index.tsx
  src/screens/FloorScreen/FloorViewerScreen.tsx
  src/screens/ImageDetailScreen/index.tsx
  src/screens/OnboardingScreen/index.tsx
  src/screens/SettingScreen/index.tsx
  src/services/validation/signUp.ts
  src/states/userStore.ts
  yarn.lock
Labels: bug, feature

#61 feat: notification screen
  assets/splash.png
  src/apis/notification.ts
  src/constants/screens.ts
  src/feature/FloorDropdown/index.tsx
  src/feature/FloorPictureList/FloorPicture.tsx
  src/feature/FloorTicket/index.tsx
  src/feature/FollowButton/index.tsx
  src/feature/NotificationList/NotificationItem.stories.tsx
  src/feature/NotificationList/NotificationItem.tsx
  src/feature/NotificationList/index.tsx
  src/feature/Routes/MainTabNavigator.tsx
  src/feature/Routes/NotificationStack.tsx
  src/screens/ImageDetailScreen/index.tsx
  src/screens/NotificationScreen/index.tsx
  src/services/date/format.ts
  src/types/notification.ts
  storybook/storyLoader.js
Labels: feature

#65 chore: disable orientation lock
  App.tsx
  src/screens/FloorScreen/EditFloorScreen.tsx
  src/screens/FloorScreen/FloorViewerScreen.tsx
  src/screens/FloorScreen/HashtagFloorScreen.tsx
  src/screens/ImageDetailScreen/index.tsx
Labels: bug

#66 Fix/issue 5
  assets/icons/NewNotification.tsx
  src/constants/common/index.ts
  src/feature/FloorPictureList/FloorPicture.tsx
  src/feature/FollowButton/index.tsx
  src/feature/GuestBookList/GuestBookItem.tsx
  src/screens/CreateFloorScreen/PictureDescriptionScreen.tsx
  src/screens/FloorScreen/EditDescriptionScreen.tsx
Labels: bug, feature

#67 Fix: issue 6
  assets/icons/Notification.tsx
  src/feature/FloorDropdown/index.tsx
  src/feature/NotificationList/index.tsx
  src/screens/CreateFloorScreen/AddHashtagScreen.tsx
  src/screens/NotificationScreen/index.tsx
  src/types/notification.ts
Labels: bug
